name: generate-snake
on:
  schedule: # 定时更新
    - cron: "0 */6 * * *"
  workflow_dispatch: # 手动触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }} # 自动获取你的用户名
          outputs: dist/snake.svg
      - name: push
        uses: EndBug/add-and-commit@v9
        with:
          message: "update snake svg"
          add: dist/snake.svg
